(function(){
'use strict';
if(document.getElementById('lore-chatbot-root')) return;

var style=document.createElement('style');
style.textContent='#lore-chatbot-root{position:fixed;right:22px;bottom:22px;z-index:99990;font-family:inherit}.lore-chat-launcher{width:64px;height:64px;border:0;border-radius:50%;background:#19352a;color:#fff;cursor:pointer;font-size:25px}.lore-chat-window{position:absolute;right:0;bottom:78px;width:min(400px,calc(100vw - 28px));height:min(570px,74vh);background:#fff;border-radius:24px;box-shadow:0 24px 70px rgba(0,0,0,.24);overflow:hidden;display:none;flex-direction:column}.lore-chat-window.open{display:flex}.lore-chat-header{padding:16px;background:#19352a;color:#fff;display:flex;justify-content:space-between}.lore-chat-close{border:0;background:transparent;color:#fff;font-size:25px;cursor:pointer}.lore-chat-messages{flex:1;overflow:auto;padding:18px;background:#f6f8f7;display:flex;flex-direction:column;gap:10px}.lore-chat-message{max-width:86%;padding:11px 14px;border-radius:16px;font-size:14px;line-height:1.55;white-space:pre-line}.bot{align-self:flex-start;background:#fff}.user{align-self:flex-end;background:#1f7a4d;color:#fff}.lore-chat-options{display:flex;flex-wrap:wrap;gap:7px}.lore-chat-option{border:1px solid #cfe0d5;background:#fff;color:#176b42;border-radius:999px;padding:8px 11px;font-weight:700;font-size:12px;cursor:pointer}.lore-chat-form{display:flex;gap:8px;padding:12px;border-top:1px solid #e3e9e5}.lore-chat-input{flex:1;border:1px solid #d7e1da;border-radius:999px;padding:11px 14px;font:inherit}.lore-chat-send{border:0;border-radius:999px;background:#1f7a4d;color:#fff;padding:0 16px;font-weight:800;cursor:pointer}';
document.head.appendChild(style);

var root=document.createElement('div');
root.id='lore-chatbot-root';
root.innerHTML='<div class="lore-chat-window" role="dialog" aria-label="Lore’s SANTÉ Assistant"><div class="lore-chat-header"><div><b>Lore’s SANTÉ Assistant</b><div style="font-size:12px;margin-top:4px">● Online now · Usually replies in minutes</div></div><button class="lore-chat-close" aria-label="Close chat">×</button></div><div class="lore-chat-messages" aria-live="polite"></div><form class="lore-chat-form"><input class="lore-chat-input" placeholder="Type your question..." autocomplete="off"><button class="lore-chat-send">Send</button></form></div><button class="lore-chat-launcher" aria-label="Open chat">💬</button>';
document.body.appendChild(root);

var win=root.querySelector('.lore-chat-window'),messages=root.querySelector('.lore-chat-messages'),input=root.querySelector('input');
function add(t,w){var m=document.createElement('div');m.className='lore-chat-message '+w;m.textContent=t;messages.appendChild(m);messages.scrollTop=messages.scrollHeight}
function opts(a){var d=document.createElement('div');d.className='lore-chat-options';a.forEach(function(x){var b=document.createElement('button');b.type='button';b.className='lore-chat-option';b.textContent=x;b.onclick=function(){handle(x)};d.appendChild(b)});messages.appendChild(d);messages.scrollTop=messages.scrollHeight}
function menu(){opts(['🌿 Explore Products','💼 Business Opportunity','🎉 About SANTÉ · 19 Years','📦 How to Order','👩‍💼 Talk to Lore'])}
function greet(){add('Kumusta! 👋 Welcome. I’m Lore’s SANTÉ Assistant. I can guide you through SANTÉ products, answer common Barley questions, explain the business opportunity, or help you connect with Lore. You can ask me in English or Filipino.','bot');menu()}

/* SANTÉ Barley FAQ knowledge base. Answers are based on the FAQ supplied by Lore. */
var FAQS=[
{keys:['how is barley juice powder processed','how is barley processed','processed','processing'],en:'According to the SANTÉ FAQ, barley grass is organically grown without chemical pesticides, herbicides or fertilizers. It is harvested when the leaves contain a broad spectrum of nutrients, then low-temperature processing is used to make the concentrate juice powder.',tl:'Ayon sa SANTÉ FAQ, ang barley grass ay organically grown nang walang chemical pesticides, herbicides o fertilizers. Inaani ito kapag malawak ang nutrient spectrum ng mga dahon, pagkatapos ay low-temperature processing ang ginagamit para maging concentrate juice powder.'},
{keys:['how do you take barley','how to take barley','how to consume barley','how do i take barley','how should i take barley','how to drink barley','paano inumin','paano ito inumin','paano gamitin'],en:'The FAQ suggests taking SANTÉ Pure Barley on an empty stomach: either about 20 minutes before a meal or 2 hours after. Use cold or room-temperature liquid and sip it slowly. For the general serving guidance in the FAQ, it says 1 teaspoon (3g) twice a day, 30 minutes before a meal. For illness, please do not self-adjust the serving; consult a qualified health professional.',tl:'Ayon sa FAQ, pinakamainam itong inumin nang walang laman ang tiyan: mga 20 minuto bago kumain o 2 oras pagkatapos kumain. Gumamit ng malamig o room-temperature na liquid at dahan-dahang inumin. Sa general serving guidance ng FAQ, 1 teaspoon (3g) dalawang beses bawat araw, 30 minuto bago kumain. Kung may karamdaman, huwag basta magdagdag ng serving nang walang payo ng health professional.'},
{keys:['empty stomach','on an empty stomach','before a meal','after a meal','with meals','take after meals','take with meals','walang laman ang tiyan'],en:'The FAQ recommends taking it on an empty stomach so the nutrients can be assimilated without other foods present. It says you can drink it anytime, but suggests taking it alone rather than with a meal.',tl:'Inirerekomenda ng FAQ na inumin ito nang walang laman ang tiyan para mas madaling ma-assimilate ang nutrients nang walang kasamang ibang pagkain. Maaari naman itong inumin anumang oras, pero iminumungkahi ng FAQ na inumin ito nang hiwalay sa pagkain.'},
{keys:['hot water','warm water','iced water','cold water','room temperature water','hot beverage','hot drink','mainit na tubig','maligamgam','malamig na tubig'],en:'For preparation, the FAQ recommends cold or room-temperature liquid and says to avoid hot, warm, iced, or hot beverages because heat is described as affecting the product’s live enzymes and nutrients.',tl:'Para sa preparation, inirerekomenda ng FAQ ang cold o room-temperature na liquid at sinasabing iwasan ang hot, warm, iced, o hot beverages dahil ayon sa FAQ ay maaaring maapektuhan ng init ang live enzymes at nutrients ng produkto.'},
{keys:['storage','store barley','refrigerator','refrigerate','where should i store','saan itago','ref','refrigerator'],en:'The FAQ says to keep SANTÉ Barley away from moisture and sunlight, tightly closed in its own jar. It advises against refrigerator storage because condensation may affect the product.',tl:'Ayon sa FAQ, ilayo ang SANTÉ Barley sa moisture at sunlight at panatilihing mahigpit na nakasara sa sariling lalagyan. Hindi nito inirerekomenda ang refrigerator dahil maaaring magkaroon ng condensation.'},
{keys:['shelf life','expire','expiration','how long does barley retain','ilang taon','expiry'],en:'The FAQ states that SANTÉ Pure Barley has a shelf life of 3 years.',tl:'Ayon sa FAQ, ang shelf life ng SANTÉ Pure Barley ay 3 taon.'},
{keys:['calories','how many calories','20 calories','calorie'],en:'The FAQ states that SANTÉ Pure Barley has 20 calories per serving.',tl:'Ayon sa FAQ, may 20 calories bawat serving ang SANTÉ Pure Barley.'},
{keys:['caffeine','coffee','energy','contains caffeine','may caffeine','may kape'],en:'No. The FAQ states that SANTÉ Pure Barley contains no caffeine. It also notes that some customers report feeling more energetic, but that is not the same as caffeine stimulation.',tl:'Wala. Ayon sa FAQ, walang caffeine ang SANTÉ Pure Barley. Binabanggit din nito na may ilang customers na nakararamdam ng mas maraming energy, pero hindi ito katulad ng caffeine stimulation.'},
{keys:['meal replacement','replace a meal','instead of food','pamalit sa pagkain'],en:'No. The FAQ says SANTÉ Pure Barley is not intended to replace a meal. It should be considered a supplement as part of an overall diet.',tl:'Hindi. Ayon sa FAQ, hindi intended ang SANTÉ Pure Barley bilang pamalit sa meal. Supplement ito na bahagi ng overall diet.'},
{keys:['weight loss','lose weight','slimming','papayat','pampapayat','timbang'],en:'The FAQ notes that SANTÉ Pure Barley has 20 calories per serving and says it can be included in a weight-loss program. It should not be treated as a guaranteed weight-loss product or substitute for a balanced diet.',tl:'Binabanggit ng FAQ na 20 calories bawat serving ang SANTÉ Pure Barley at maaari itong isama sa weight-loss program. Hindi ito dapat ituring na garantisadong pampapayat o kapalit ng balanced diet.'},
{keys:['capsules','capsule','powder','difference between capsules','capsule vs powder','pulbos','kapsula'],en:'The FAQ says the capsules and juice powder are the same product, with the powder being instantly soluble. It describes the powder as being assimilated more rapidly than the capsules.',tl:'Ayon sa FAQ, pareho ang produkto sa capsules at juice powder, at ang powder ay instantly soluble. Inilalarawan ng FAQ na mas mabilis itong ma-assimilate kaysa capsules.'},
{keys:['taste','what does it taste like','masarap','lasa'],en:'Taste can vary because it is a natural product. The FAQ suggests starting with a small amount if you are new to barley juice; some people also mix it with fruit juice. Capsules are another option if you prefer not to taste the powder.',tl:'Maaaring mag-iba ang lasa dahil natural product ito. Iminumungkahi ng FAQ na magsimula sa maliit na amount kung bago ka sa barley juice; may ilan ding naghahalo nito sa fruit juice. May capsules din kung ayaw mong tikman ang powder.'},
{keys:['gluten','allergy','allergic reaction','grass allergy','barley allergy','gluten free','may gluten','allergy sa damo'],en:'The FAQ says the juice powder comes from young barley grass leaves rather than mature barley grain and states that its ingredients contain no gluten. It also notes that people with grass allergies may rarely react. If you have a known allergy or previous reaction, consult a health professional before using it.',tl:'Ayon sa FAQ, ang juice powder ay mula sa young barley grass leaves at hindi sa mature barley grain, at sinasabi nitong walang gluten ang ingredients. Binabanggit din nito na maaaring magkaroon ng rare reaction ang may grass allergy. Kung may known allergy o dati nang reaction, kumonsulta muna sa health professional bago gamitin.'},
{keys:['medication','medicine','taking medication','take with medicine','gamot','umiinom ng gamot'],en:'The FAQ says people taking medication should consider whether their health practitioner has restricted green vegetables. Because medication interactions can depend on the individual and the medicine, it is safest to check with your health professional before adding a supplement.',tl:'Ayon sa FAQ, dapat isaalang-alang ng umiinom ng gamot kung may ipinagbawal ang kanilang health practitioner na green vegetables. Dahil depende sa tao at gamot ang possible interactions, mas ligtas na kumonsulta muna sa health professional bago magdagdag ng supplement.'},
{keys:['diabetes','diabetic','blood sugar','asukal sa dugo','diabetic ba'],en:'The FAQ says there are no known adverse effects associated with SANTÉ Pure Barley and blood sugar levels, while also encouraging people with concerns to consult their health practitioner. The FAQ is not a substitute for medical advice, especially if you use glucose-lowering medication.',tl:'Ayon sa FAQ, walang kilalang adverse effects na iniuugnay nito sa blood sugar levels, pero hinihikayat pa rin ang may concerns na kumonsulta sa health practitioner. Hindi kapalit ng medical advice ang FAQ, lalo na kung umiinom ng gamot para sa blood sugar.'},
{keys:['kidney','renal failure','kidney disease','kidney disorder','bato','renal'],en:'The FAQ specifically advises people with kidney disorders, kidney disease, or renal failure to consult their health practitioner because SANTÉ Barley contains potassium. It cites 214 mg of potassium in a 5-gram serving in its nutritional analysis.',tl:'Partikular na sinasabi ng FAQ na ang may kidney disorder, kidney disease, o renal failure ay dapat kumonsulta sa health practitioner dahil may potassium ang SANTÉ Barley. Binabanggit nito ang 214 mg potassium sa 5-gram serving ayon sa nutritional analysis nito.'},
{keys:['pregnant','pregnancy','prenatal','unborn baby','buntis','pagbubuntis'],en:'The FAQ says SANTÉ Pure Barley can be used as a prenatal supplement. Because pregnancy has individual nutritional and medical considerations, please confirm with your prenatal healthcare provider before using any supplement.',tl:'Sinasabi ng FAQ na maaaring gamitin ang SANTÉ Pure Barley bilang prenatal supplement. Dahil may kanya-kanyang nutritional at medical considerations ang pagbubuntis, mas mabuting kumpirmahin muna ito sa prenatal healthcare provider bago gumamit ng supplement.'},
{keys:['stomach','upset stomach','acid','hyperacidity','tiyan','asim'],en:'The FAQ describes SANTÉ Pure Barley as mildly alkaline and says it may help settle the stomach. If you have persistent or severe stomach symptoms, please consult a health professional rather than relying on a supplement.',tl:'Inilalarawan ng FAQ ang SANTÉ Pure Barley bilang mildly alkaline at sinasabing maaari itong makatulong sa pag-settle ng tiyan. Kung tuloy-tuloy o matindi ang sintomas sa tiyan, kumonsulta sa health professional at huwag umasa sa supplement lamang.'},
{keys:['diarrhea','constipation','regularity','pagtatae'],en:'The FAQ says SANTÉ Pure Barley has traditionally been used to promote regularity and says it does not cause constipation. If diarrhea or constipation is persistent or severe, seek medical advice.',tl:'Ayon sa FAQ, tradisyonal itong ginagamit upang makatulong sa regularity at sinasabing hindi ito nagdudulot ng constipation. Kung tuloy-tuloy o matindi ang diarrhea o constipation, magpatingin sa health professional.'},
{keys:['digestive enzymes','enzymes','amylase','enzyme'],en:'Yes. The FAQ states that SANTÉ Pure Barley contains many enzymes, including digestive enzymes such as amylase.',tl:'Oo. Ayon sa FAQ, maraming enzymes ang SANTÉ Pure Barley, kabilang ang digestive enzymes tulad ng amylase.'},
{keys:['antioxidant','antioxidants','orac','free radicals','sod','chlorophyll','beta carotene'],en:'The FAQ describes SANTÉ Barley as containing naturally occurring antioxidants and nutrients, including beta-carotene, chlorophyll, SOD, catalase, Lutonarin, Saponarin, polyphenol oxidase, vitamin E, phosphorus, and zinc. These are presented in the FAQ as naturally occurring nutrients, not ingredients added to the product.',tl:'Inilalarawan ng FAQ ang SANTÉ Barley na may naturally occurring antioxidants at nutrients gaya ng beta-carotene, chlorophyll, SOD, catalase, Lutonarin, Saponarin, polyphenol oxidase, vitamin E, phosphorus, at zinc. Ayon sa FAQ, natural na nasa produkto ang mga ito at hindi mga ingredient na idinagdag.'},
{keys:['why barley juice','why barley','what is barley good for','benefits of barley','benefits','bakit barley','ano ang benefits'],en:'The FAQ describes barley juice as a whole-food supplement containing naturally occurring vitamins, minerals, enzymes, protein, chlorophyll, antioxidants and other phytochemicals. I can explain a specific FAQ claim if you tell me what you want to know.',tl:'Inilalarawan ng FAQ ang barley juice bilang whole-food supplement na may naturally occurring vitamins, minerals, enzymes, protein, chlorophyll, antioxidants at iba pang phytochemicals. Maaari kong ipaliwanag ang specific FAQ claim na gusto mong malaman.'},
{keys:['how much','serving','servings','dose','dosage','ilang kutsarita','ilang beses'],en:'For general use, the FAQ gives 1 teaspoon (3g) twice a day, 30 minutes before a meal. It also contains higher serving suggestions for people who are ill, but the chatbot will not recommend increasing the serving for illness; please consult a qualified health professional for individualized guidance.',tl:'Para sa general use, ang serving guidance ng FAQ ay 1 teaspoon (3g) dalawang beses bawat araw, 30 minuto bago kumain. May mas mataas na serving suggestions din ito para sa may sakit, pero hindi magrerekomenda ang chatbot ng pagtaas ng serving para sa illness; kumonsulta sa qualified health professional para sa individualized guidance.'},
{keys:['feel worse','feeling worse','detox','detoxification','cleansing reaction','headache','nausea','vomiting','rash','fatigue','insomnia','nangingilo','masama ang pakiramdam'],en:'The FAQ attributes symptoms such as fatigue, rash, headache, nausea, vomiting, diarrhea, insomnia or constipation to a possible “cleansing/detoxification” reaction. That explanation is a claim in the supplied FAQ, not a medical diagnosis. If symptoms are severe, persistent, worsening, or concerning, stop using the product and seek medical care.',tl:'Iniuugnay ng FAQ ang mga sintomas gaya ng fatigue, rash, headache, nausea, vomiting, diarrhea, insomnia o constipation sa posibleng “cleansing/detoxification” reaction. Claim ito sa supplied FAQ at hindi medical diagnosis. Kung matindi, tuloy-tuloy, lumalala, o nakababahala ang sintomas, itigil muna ang paggamit at magpatingin sa health professional.'},
{keys:['cranberry','prune juice','carbonated drinks','soft drinks'],en:'The FAQ recommends not mixing SANTÉ Pure Barley with hot drinks, cranberry or prune juice, or carbonated drinks because it says heat and acidity can affect enzymatic activity.',tl:'Ayon sa FAQ, hindi inirerekomendang ihalo ang SANTÉ Pure Barley sa hot drinks, cranberry o prune juice, o carbonated drinks dahil sinasabi nitong maaaring maapektuhan ng heat at acidity ang enzymatic activity.'},
{keys:['prepare ahead','keep after preparation','prepared drink','20 minutes','how long after mixing','gaano katagal'],en:'The FAQ recommends drinking the prepared SANTÉ Pure Barley soon after mixing and says it should be consumed within about 20 minutes.',tl:'Inirerekomenda ng FAQ na inumin ang prepared SANTÉ Pure Barley agad pagkatapos ihalo at sinasabing dapat itong ma-consume sa loob ng humigit-kumulang 20 minuto.'}
];

function containsKey(q,key){
  if(key.indexOf(' ')>=0) return q.indexOf(key)>=0;
  return new RegExp('(^|[^a-z])'+key.replace(/[.*+?^${}()|[\\]\\]/g,'\\$&')+'([^a-z]|$)','i').test(q);
}
function isFilipino(q){return /(paano|pwede|maaari|may|walang|ano|bakit|ilang|inom|inumin|kain|tiyan|gamot|buntis|pagbubuntis|bato|asukal|lasa|itago|taon|kutsarita|beses|masama|pampapayat)/i.test(q)}
function faqReply(q){
  var best=null,bestScore=0;
  FAQS.forEach(function(item){
    var score=0;
    item.keys.forEach(function(k){if(containsKey(q,k)) score+=k.indexOf(' ')>=0?3:1});
    if(score>bestScore){best=item;bestScore=score}
  });
  if(!best) return null;
  return isFilipino(q)?best.tl:best.en;
}

function handle(t){
  add(t,'user');
  var q=t.toLowerCase().trim();

  if(q==='🌿 explore products'||q==='explore products'){location.href='/#products';return}
  if(q==='📦 how to order'||q==='how to order'){add('You can explore the products and place an order through Lore’s SANTÉ partner shop.','bot');opts(['🌿 Explore Products','👩‍💼 Talk to Lore','Back to Menu']);return}
  if(q==='👩‍💼 talk to lore'||q==='talk to lore'){location.href='/#contact';return}

  if(q.includes('about santé')||q.includes('about sante')||q.includes('19 years')){add('🎉 SANTÉ was founded in 2007 and celebrates 19 years in 2026. Would you like to explore the company story and the different paths available?','bot');opts(['Open About SANTÉ','Back to Menu']);return}
  if(q.includes('open about santé')||q.includes('open about sante')){location.href='/about-sante.html';return}
  if(q.includes('back to menu')){add('What would you like to explore next?','bot');menu();return}
  if(q.includes('business')){add('Would you like to learn how to become an Affiliate or how earning in the business works?','bot');opts(['How to Become an Affiliate','💰 How to Earn in the Business','Talk to Lore','Back to Menu']);return}
  if(q.includes('how to earn')){add('The website has a dedicated visual guide explaining the five earning opportunities with simple examples. Actual earnings depend on qualifications and program rules.','bot');opts(['📊 Explore the 5 Ways to Earn','Back to Menu']);return}
  if(q.includes('5 ways')){location.href='/ways-to-earn.html';return}

  var faq=faqReply(q);
  if(faq){add(faq,'bot');opts(['🌿 Explore Products','📦 How to Order','👩‍💼 Talk to Lore','Back to Menu']);return}

  if(q.includes('product')||q.includes('barley')){location.href='/#products';return}
  if(q.includes('order')||q.includes('buy')){add('You can explore the products and place an order through Lore’s SANTÉ partner shop.','bot');opts(['🌿 Explore Products','👩‍💼 Talk to Lore','Back to Menu']);return}
  if(q.includes('lore')||q.includes('agent')||q.includes('contact')){location.href='/#contact';return}

  add('I can answer many common SANTÉ Barley questions from our FAQ. Try asking things like “How do I take Barley?”, “Does it contain caffeine?”, “Can diabetics take it?”, “How should I store it?”, or “What is the difference between powder and capsules?”','bot');
  opts(['🌿 Explore Products','💼 Business Opportunity','📦 How to Order','👩‍💼 Talk to Lore']);
}

root.querySelector('.lore-chat-launcher').onclick=function(){win.classList.toggle('open');if(win.classList.contains('open')&&!messages.children.length)greet();if(win.classList.contains('open'))input.focus()};
root.querySelector('.lore-chat-close').onclick=function(){win.classList.remove('open')};
root.querySelector('form').onsubmit=function(e){e.preventDefault();var t=input.value.trim();if(t){input.value='';handle(t)}};
})();