const API='https://script.google.com/macros/s/AKfycbyAH0bwPH0cH4dUFFrO45vjc697oO8I9WhIuzaxi1jCemF-dsgSpicUfnGdnoJOUBJO/exec';
let leads=[];
const $=s=>document.querySelector(s);
function escapeHtml(v=''){return String(v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function getToken(){return sessionStorage.getItem('santeCRMToken')||''}
async function apiPost(payload){const r=await fetch(API,{method:'POST',body:JSON.stringify(payload),headers:{'Content-Type':'text/plain;charset=utf-8'}});const data=await r.json();if(!data.ok)throw new Error(data.error||'Request failed');return data}
async function handleLogin(e){if(e)e.preventDefault();const code=$('#accessCode').value;const error=$('#loginError'),btn=$('#openCrmBtn');btn.disabled=true;btn.textContent='Opening…';try{const data=await apiPost({action:'login',accessCode:code});if(!data.token)throw new Error('Authentication failed');sessionStorage.setItem('santeCRMToken',data.token);error.hidden=true;$('#accessCode').value='';openApp()}catch(err){error.textContent='Incorrect access code or authentication is not configured yet.';error.hidden=false;$('#accessCode').focus()}finally{btn.disabled=false;btn.textContent='Open CRM →'}return false}
$('#loginForm').addEventListener('submit',handleLogin);
$('#logoutBtn').onclick=()=>{sessionStorage.removeItem('santeCRMToken');location.reload()};
function openApp(){$('#loginScreen').hidden=true;$('#app').hidden=false;loadLeads()}
if(getToken())openApp();
async function loadLeads(){['#refreshBtn','#refreshBtn2','#mobileRefresh'].forEach(id=>{const b=$(id);if(b)b.disabled=true});$('#lastUpdated').textContent='Refreshing leads…';try{const data=await apiPost({action:'list',token:getToken()});leads=data.leads||[];render();$('#lastUpdated').textContent='Updated '+new Date().toLocaleString()}catch(err){console.error(err);if(/unauthor|session|token/i.test(err.message)){sessionStorage.removeItem('santeCRMToken');location.reload();return}$('#lastUpdated').textContent='Could not load leads. Check Apps Script deployment.';alert('CRM could not load leads. Please refresh or check the secure Apps Script deployment.')}finally{['#refreshBtn','#refreshBtn2','#mobileRefresh'].forEach(id=>{const b=$(id);if(b)b.disabled=false})}}
['#refreshBtn','#refreshBtn2','#mobileRefresh'].forEach(id=>{const b=$(id);if(b)b.onclick=loadLeads});
$('#searchInput').oninput=render;$('#statusFilter').onchange=render;
function filtered(){const q=$('#searchInput').value.toLowerCase(),s=$('#statusFilter').value;return leads.filter(x=>!s||x.status===s).filter(x=>Object.values(x).join(' ').toLowerCase().includes(q))}
function render(){const rows=filtered();const count=s=>leads.filter(x=>x.status===s).length;$('#totalCount').textContent=leads.length;$('#newCount').textContent=count('New');$('#contactedCount').textContent=count('Contacted');$('#followupCount').textContent=count('Follow-up');$('#convertedCount').textContent=count('Converted');$('#leadSummary').textContent=rows.length+' lead'+(rows.length===1?'':'s')+' shown';$('#leadTable').innerHTML=rows.map(x=>'<tr><td><span class="lead-name">'+escapeHtml(x.fullName)+'</span><span class="lead-email">'+escapeHtml(x.email)+'</span></td><td>'+escapeHtml(x.country)+'</td><td>'+escapeHtml(x.interest||x.package)+'</td><td>'+escapeHtml(x.dateTime)+'</td><td><span class="badge '+escapeHtml(x.status).replace(/ /g,'.')+'">'+escapeHtml(x.status)+'</span></td><td><button class="view-btn" data-row="'+x.row+'">View →</button></td></tr>').join('');$('#emptyState').hidden=rows.length!==0;document.querySelectorAll('.view-btn').forEach(b=>b.onclick=()=>showLead(leads.find(x=>x.row==b.dataset.row)))}
function showLead(x){const d=$('#leadDialog');const phone=(x.phone||'').replace(/\D/g,'');$('#leadDetail').innerHTML='<div class="detail"><p class="eyebrow">LEAD DETAILS</p><h2>'+escapeHtml(x.fullName)+'</h2><p class="detail-sub">'+escapeHtml(x.interest||'Website lead')+' · '+escapeHtml(x.country||'No country')+'</p><div class="detail-grid"><label>Email<input value="'+escapeHtml(x.email)+'" disabled></label><label>Mobile / WhatsApp<input value="'+escapeHtml(x.phone)+'" disabled></label><label>Country<input value="'+escapeHtml(x.country)+'" disabled></label><label>Status<select id="editStatus">'+['New','Contacted','Follow-up','Converted','Not Interested'].map(s=>'<option '+(x.status===s?'selected':'')+'>'+s+'</option>').join('')+'</select></label><label class="full">Message<textarea rows="4" disabled>'+escapeHtml(x.message)+'</textarea></label><label class="full">CRM Notes<textarea id="editNotes" rows="4" placeholder="Add your follow-up notes…">'+escapeHtml(x.notes||'')+'</textarea></label><label>Follow-up date<input id="editFollowup" type="date" value="'+escapeHtml(x.followUp||'')+'"></label></div><div class="detail-actions"><a class="whatsapp" target="_blank" href="https://wa.me/'+phone+'?text='+encodeURIComponent('Hi '+x.fullName.split(' ')[0]+', this is Lore from SANTÉ Wellness. 👋')+'">💬 WhatsApp Lead</a><button class="primary" id="saveLead">Save changes</button></div><p class="save-note" id="saveNote">Changes are saved back to the Google Sheet.</p></div>';d.showModal();$('#saveLead').onclick=()=>saveLead(x.row)}
$('#closeDialog').onclick=()=>$('#leadDialog').close();
async function saveLead(row){const payload={action:'update',token:getToken(),row:Number(row),status:$('#editStatus').value,notes:$('#editNotes').value,followUp:$('#editFollowup').value};const btn=$('#saveLead');btn.disabled=true;btn.textContent='Saving…';try{await apiPost(payload);$('#saveNote').textContent='✓ Saved to Google Sheets.';await loadLeads()}catch(e){$('#saveNote').textContent='Could not save. Your secure session may have expired.';console.error(e)}finally{btn.disabled=false;btn.textContent='Save changes'}}