(function(){'use strict';
var LANGS=[['en','🇬🇧','English'],['fil','🇵🇭','Filipino'],['es','🇪🇸','Español'],['fr','🇫🇷','Français'],['ar','🇸🇦','العربية'],['zh-CN','🇨🇳','简体中文']];
var selector='[data-ml-ignore],script,style';
var state={original:[],translated:false};
function addStyles(){if(document.getElementById('multilingual-addon-styles'))return;var s=document.createElement('style');s.id='multilingual-addon-styles';s.textContent='.ml-switcher{position:fixed;right:18px;bottom:86px;z-index:99990;font:600 14px/1.2 Arial,sans-serif}.ml-toggle{border:1px solid rgba(32,54,45,.18);background:#fff;color:#20362d;border-radius:999px;padding:11px 15px;box-shadow:0 8px 28px rgba(0,0,0,.14);cursor:pointer}.ml-menu{display:none;position:absolute;right:0;bottom:50px;width:190px;max-height:310px;overflow:auto;padding:8px;background:#fff;border-radius:16px;box-shadow:0 14px 40px rgba(0,0,0,.2)}.ml-switcher.open .ml-menu{display:block}.ml-menu button{display:block;width:100%;padding:11px 12px;border:0;background:transparent;text-align:left;border-radius:10px;color:#20362d;cursor:pointer;font:600 14px Arial}.ml-menu button:hover,.ml-menu button.active{background:#eef6f0}.ml-loading{position:fixed;inset:0;z-index:100000;background:rgba(255,255,255,.72);display:flex;align-items:center;justify-content:center;font:700 16px Arial;color:#20362d;backdrop-filter:blur(2px)}html[dir="rtl"] body{direction:rtl;text-align:right}html[dir="rtl"] .ml-switcher{left:18px;right:auto}';document.head.appendChild(s)}
function collect(){if(state.original.length)return;var w=document.createTreeWalker(document.body,NodeFilter.SHOW_TEXT,{acceptNode:function(n){if(!n.nodeValue.trim())return NodeFilter.FILTER_REJECT;var p=n.parentElement;if(!p||p.closest(selector)||p.closest('.ml-switcher,.location-modal,.wellness-lightbox'))return NodeFilter.FILTER_REJECT;return NodeFilter.FILTER_ACCEPT}});var n;while(n=w.nextNode())state.original.push({node:n,text:n.nodeValue})}
function restore(){state.original.forEach(function(x){x.node.nodeValue=x.text});document.documentElement.lang='en';document.documentElement.dir='ltr';document.title='SANTÉ Wellness | Products & Business Opportunity';state.translated=false}
function chunks(a,size){var r=[];for(var i=0;i<a.length;i+=size)r.push(a.slice(i,i+size));return r}
async function translate(lang){if(lang==='en'){restore();localStorage.setItem('santewithlore-language','en');return}collect();var overlay=document.createElement('div');overlay.className='ml-loading';overlay.textContent='Translating website…';overlay.setAttribute('data-ml-ignore','');document.body.appendChild(overlay);try{restore();var texts=state.original.map(function(x){return x.text});var batches=chunks(texts,35);var out=[];for(var i=0;i<batches.length;i++){var q=batches[i].map(encodeURIComponent).join('&q=');var url='https://translate.googleapis.com/translate_a/single?client=gtx&sl=en&tl='+encodeURIComponent(lang)+'&dt=t&q='+q;var res=await fetch(url);var data=await res.json();for(var j=0;j<data.length;j++){var item=data[j];var translated='';if(Array.isArray(item))item.forEach(function(part){if(Array.isArray(part)&&part[0])translated+=part[0]});out.push(translated||batches[i][j])}}state.original.forEach(function(x,k){if(out[k])x.node.nodeValue=out[k]});document.documentElement.lang=lang;document.documentElement.dir=lang==='ar'?'rtl':'ltr';document.title=(lang==='zh-CN'?'SANTÉ Wellness｜产品与商业机会':document.title);state.translated=true;localStorage.setItem('santewithlore-language',lang)}catch(e){console.error('Translation add-on error',e);alert('Translation could not be loaded. Please try again.')}finally{overlay.remove()}}
function build(){addStyles();var box=document.createElement('div');box.className='ml-switcher';box.setAttribute('data-ml-ignore','');box.innerHTML='<button class="ml-toggle" type="button" aria-expanded="false">🌐 Language</button><div class="ml-menu" role="menu"></div>';var menu=box.querySelector('.ml-menu');LANGS.forEach(function(l){var b=document.createElement('button');b.type='button';b.dataset.lang=l[0];b.textContent=l[1]+' '+l[2];b.addEventListener('click',function(){translate(l[0]);box.classList.remove('open');box.querySelector('.ml-toggle').setAttribute('aria-expanded','false');menu.querySelectorAll('button').forEach(function(x){x.classList.toggle('active',x===b)})});menu.appendChild(b)});box.querySelector('.ml-toggle').addEventListener('click',function(){box.classList.toggle('open');this.setAttribute('aria-expanded',box.classList.contains('open')?'true':'false')});document.body.appendChild(box);var saved=localStorage.getItem('santewithlore-language');if(saved&&saved!=='en')setTimeout(function(){var b=menu.querySelector('[data-lang="'+saved+'"]');if(b)b.click()},400)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();