(function(){'use strict';
var LANGS=[['en','🇬🇧','English'],['fil','🇵🇭','Filipino'],['es','🇪🇸','Español'],['fr','🇫🇷','Français'],['ar','🇸🇦','العربية'],['zh-CN','🇨🇳','简体中文']];
function addStyles(){if(document.getElementById('multilingual-addon-styles'))return;var s=document.createElement('style');s.id='multilingual-addon-styles';s.textContent='.ml-switcher{position:fixed;right:18px;bottom:86px;z-index:99990;font:600 14px/1.2 Arial,sans-serif}.ml-toggle{border:1px solid rgba(32,54,45,.18);background:#fff;color:#20362d;border-radius:999px;padding:11px 15px;box-shadow:0 8px 28px rgba(0,0,0,.14);cursor:pointer}.ml-menu{display:none;position:absolute;right:0;bottom:50px;width:190px;max-height:310px;overflow:auto;padding:8px;background:#fff;border-radius:16px;box-shadow:0 14px 40px rgba(0,0,0,.2)}.ml-switcher.open .ml-menu{display:block}.ml-menu button{display:block;width:100%;padding:11px 12px;border:0;background:transparent;text-align:left;border-radius:10px;color:#20362d;cursor:pointer;font:600 14px Arial}.ml-menu button:hover,.ml-menu button.active{background:#eef6f0}.ml-loading{position:fixed;inset:0;z-index:100000;background:rgba(255,255,255,.72);display:flex;align-items:center;justify-content:center;font:700 16px Arial;color:#20362d;backdrop-filter:blur(2px)}#google_translate_element{position:absolute;left:-9999px;top:-9999px;visibility:hidden;pointer-events:none}.goog-te-banner-frame.skiptranslate{display:none!important}body{top:0!important}html[dir="rtl"] .ml-switcher{left:18px;right:auto}';document.head.appendChild(s)}
function cookie(name,value){document.cookie=name+'='+value+';path=/;max-age=31536000;SameSite=Lax'}
function clearTranslateCookie(){cookie('googtrans','');cookie('googtrans',';expires=Thu, 01 Jan 1970 00:00:00 GMT')}
function loadGoogleTranslator(){return new Promise(function(resolve,reject){if(window.google&&google.translate&&google.translate.TranslateElement){resolve();return}window.googleTranslateElementInit=function(){try{new google.translate.TranslateElement({pageLanguage:'en',includedLanguages:'fil,es,fr,ar,zh-CN',autoDisplay:false},'google_translate_element');resolve()}catch(e){reject(e)}};var old=document.querySelector('script[data-google-translate-addon]');if(old){var tries=0;var timer=setInterval(function(){if(window.google&&google.translate&&google.translate.TranslateElement){clearInterval(timer);resolve()}else if(++tries>100){clearInterval(timer);reject(new Error('Google Translate timed out'))}},100);return}var script=document.createElement('script');script.src='https://translate.google.com/translate_a/element.js?cb=googleTranslateElementInit';script.async=true;script.setAttribute('data-google-translate-addon','true');script.onerror=function(){reject(new Error('Google Translate failed to load'))};document.head.appendChild(script)})}
function changeLanguage(lang){var overlay=document.createElement('div');overlay.className='ml-loading';overlay.textContent=lang==='en'?'Restoring English…':'Translating website…';document.body.appendChild(overlay);try{if(lang==='en'){clearTranslateCookie();localStorage.setItem('santewithlore-language','en');setTimeout(function(){location.reload()},100);return}cookie('googtrans','/en/'+lang);localStorage.setItem('santewithlore-language',lang);setTimeout(function(){location.reload()},100)}catch(e){overlay.remove();alert('Translation could not be loaded. Please try again.')}}
function build(){addStyles();var host=document.createElement('div');host.id='google_translate_element';host.setAttribute('aria-hidden','true');document.body.appendChild(host);loadGoogleTranslator().catch(function(e){console.error('Google Translate add-on error',e)});var box=document.createElement('div');box.className='ml-switcher';box.setAttribute('data-ml-ignore','');box.innerHTML='<button class="ml-toggle" type="button" aria-expanded="false">🌐 Language</button><div class="ml-menu" role="menu"></div>';var menu=box.querySelector('.ml-menu');var saved=localStorage.getItem('santewithlore-language')||'en';LANGS.forEach(function(l){var b=document.createElement('button');b.type='button';b.dataset.lang=l[0];b.textContent=l[1]+' '+l[2];if(saved===l[0])b.classList.add('active');b.addEventListener('click',function(){if(l[0]===saved){box.classList.remove('open');return}changeLanguage(l[0]);box.classList.remove('open')});menu.appendChild(b)});box.querySelector('.ml-toggle').addEventListener('click',function(){box.classList.toggle('open');this.setAttribute('aria-expanded',box.classList.contains('open')?'true':'false')});document.body.appendChild(box)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',build);else build();
})();