/* Package cards and location-aware registration links. */
(function(){
  const preferred={src:'image/sante-barley-preferred-pack.png',alt:'SANTÉ Barley Preferred Pack'};
  const intro={src:'image/sante-barley-intro-pack.png',alt:'SANTÉ Barley Intro Pack'};
  const packages=[
    {key:'starter',stars:'⭐',label:'STARTER PACKAGE',owner:'1 Star Business Owner',title:'Start your SANTÉ business journey',items:['2 boxes of SANTÉ Barley Powder, 30 sachets each','1 SANTÉ Barley Canister, 200g']},
    {key:'builder',stars:'⭐⭐',label:'BUILDER PACK',owner:'2 Star Business Owner',title:'Build your product foundation',items:['5 boxes of SANTÉ Barley Powder, 30 sachets each','3 boxes of Barley Trial Pack, 10 sachets each','4 SANTÉ Barley Canisters, 200g each']},
    {key:'extreme',stars:'⭐⭐⭐',label:'EXTREME PACK',owner:'3 Star Business Owner',title:'Take your business journey further',items:['13 boxes of SANTÉ Barley Powder, 30 sachets each','8 boxes of Barley Trial Pack, 10 sachets each','9 SANTÉ Barley Canisters, 200g each']},
    {key:'ultimate',stars:'⭐⭐⭐⭐',label:'ULTIMATE PACK',owner:'4 Star Business Owner',title:'A larger package for your next step',items:['32 boxes of SANTÉ Barley Powder, 30 sachets each','22 boxes of Barley Trial Pack, 10 sachets each','22 SANTÉ Barley Canisters, 200g each']},
    {key:'global',stars:'⭐⭐⭐⭐⭐',label:'GLOBAL ULTIMATE / GLOBAL FRANCHISEE',owner:'5 Star Business Owner',title:'Explore the Global Ultimate package',items:['45 boxes of SANTÉ Barley Powder, 30 sachets each','45 boxes of Barley Trial Pack, 10 sachets each','45 SANTÉ Barley Canisters, 200g each','45 boxes of SANTÉ Barley Capsules, 60 veggie caps per box']}
  ];
  const links={
    preferred:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=preferred',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=preferred'},
    intro:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=intro',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=intro'},
    starter:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=starter',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=starter'},
    builder:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=builder',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=builder'},
    extreme:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=extreme',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=extreme'},
    ultimate:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=ultimate',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=ultimate'},
    global:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=global',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=global'}
  };
  function addStyle(){if(document.getElementById('package-final-style'))return;const s=document.createElement('style');s.id='package-final-style';s.textContent=`.package-card .package-image-wrap{width:100%;height:300px;margin:0 0 20px;display:flex;align-items:center;justify-content:center;overflow:hidden;border-radius:0;background:linear-gradient(135deg,#f5f7f4,#eef2ee)}.package-card .package-image-wrap img{width:100%;height:100%;object-fit:contain;display:block}.package-card .package-discount{display:inline-flex;align-items:center;gap:7px;margin:4px 0 12px;padding:8px 12px;border-radius:999px;background:#e8f4eb;color:#176b42;font-weight:800;font-size:.9rem}.business-packages{margin-top:64px}.business-packages-head{max-width:760px;margin:0 auto 32px;text-align:center}.business-packages-head h2{margin:0 0 10px;color:#19352a}.business-packages-head p{margin:0;color:#52655d}.business-package-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:24px}.business-package-card{padding:30px;border:1px solid #dce6df;border-radius:24px;background:#fff;box-shadow:0 12px 35px rgba(16,61,43,.08)}.business-package-card:last-child{grid-column:1/-1}.business-package-stars{letter-spacing:3px;margin-bottom:12px}.business-package-eyebrow{font-size:.78rem;font-weight:800;letter-spacing:.12em;color:#24764b}.business-package-card h3{margin:10px 0 6px;color:#19352a;font-size:1.45rem}.business-package-owner{margin:0 0 18px;font-weight:700;color:#527064}.business-package-card ul{padding-left:20px;margin:0 0 18px;color:#42554d}.business-package-card li{margin:8px 0}.business-package-choice{padding:13px 15px;border-radius:14px;background:#f2f7f3;color:#285a3e;font-size:.95rem;margin-bottom:20px}.business-package-card button{border:0;border-radius:999px;padding:13px 20px;background:#176b42;color:#fff;font:inherit;font-weight:800;cursor:pointer}.package-location-modal[hidden]{display:none!important}.package-location-modal{position:fixed;inset:0;z-index:11000;display:grid;place-items:center;padding:20px;background:#0d251b7a}.package-location-box{width:min(560px,100%);background:#fff;border-radius:24px;padding:34px;box-shadow:0 25px 70px #103d2b47}.package-location-box h2{margin:0 0 10px;color:#19352a}.package-location-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px}.package-location-actions a{display:block;padding:16px;border:1px solid #dce6df;border-radius:16px;text-decoration:none;color:#19352a;font-weight:800;background:#f8f8f4}.package-location-close{margin-top:18px;border:0;background:transparent;font:inherit;color:#496158;cursor:pointer}@media(max-width:700px){.package-card .package-image-wrap{height:220px}.business-package-grid{grid-template-columns:1fr}.business-package-card:last-child{grid-column:auto}}@media(max-width:600px){.package-location-actions{grid-template-columns:1fr}}`;document.head.appendChild(s)}
  function modal(){let m=document.querySelector('.package-location-modal');if(m)return m;m=document.createElement('div');m.className='package-location-modal';m.hidden=true;m.innerHTML='<div class="package-location-box" role="dialog" aria-modal="true"><h2>Choose your location</h2><p>Select where you are registering from to continue to the exact SANTÉ package page.</p><div class="package-location-actions"><a class="package-ph" target="_blank" rel="noopener">🇵🇭 Philippines</a><a class="package-global" target="_blank" rel="noopener">🌎 Global / Outside the Philippines</a></div><button class="package-location-close" type="button">← Cancel</button></div>';document.body.appendChild(m);const close=()=>m.hidden=true;m.querySelector('.package-location-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};return m}
  function choose(key){const m=modal(),d=links[key];m.querySelector('.package-ph').href=d.ph;m.querySelector('.package-global').href=d.global;m.hidden=false}
  function addBusinessPackages(section){if(document.getElementById('business-packages'))return;const wrap=document.createElement('section');wrap.id='business-packages';wrap.className='business-packages';wrap.innerHTML='<div class="business-packages-head"><p class="eyebrow">BUSINESS PACKAGES</p><h2>Choose the package that fits your starting point</h2><p>Review the included products and select your location before continuing to the official SANTÉ registration page.</p></div><div class="business-package-grid"></div>';const grid=wrap.querySelector('.business-package-grid');packages.forEach(p=>{const card=document.createElement('article');card.className='business-package-card';card.innerHTML=`<div class="business-package-stars">${p.stars}</div><div class="business-package-eyebrow">${p.label}</div><h3>${p.title}</h3><p class="business-package-owner">${p.owner}</p><ul>${p.items.map(x=>'<li>'+x+'</li>').join('')}</ul><div class="business-package-choice">Product selection options may be available during registration, allowing you to choose products you prefer where applicable.</div><button type="button">Choose ${p.label}</button>`;card.querySelector('button').onclick=()=>choose(p.key);grid.appendChild(card)});section.parentNode.insertBefore(wrap,section.nextSibling)}
  function apply(){const section=document.querySelector('.package-restore');if(!section)return setTimeout(apply,150);const cards=section.querySelectorAll('.package-card');if(cards.length<2)return setTimeout(apply,150);addStyle();[[cards[0],preferred],[cards[1],intro]].forEach(([card,data])=>{let wrap=card.querySelector('.package-image-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='package-image-wrap';card.insertBefore(wrap,card.firstChild)}let img=wrap.querySelector('img');if(!img){img=document.createElement('img');wrap.appendChild(img)}img.src=data.src;img.alt=data.alt;img.loading='eager'});const left=cards[0],right=cards[1];const leftLabel=left.querySelector('.eyebrow');if(leftLabel)leftLabel.textContent='PREFERRED / AFFILIATE PACK';const leftTitle=left.querySelector('h3');if(leftTitle)leftTitle.textContent='Start with products. Enjoy preferred pricing.';const leftList=left.querySelector('ul');if(leftList)leftList.innerHTML='<li>2 boxes of SANTÉ Barley Powder, 10 sachets each</li><li>Automatic registration</li><li>30% lifetime discount</li>';const rightLabel=right.querySelector('.eyebrow');if(rightLabel)rightLabel.textContent='INTRO PACK';const rightTitle=right.querySelector('h3');if(rightTitle)rightTitle.textContent='Ready to take the next step?';const rightList=right.querySelector('ul');if(rightList)rightList.innerHTML='<li>2 boxes of SANTÉ Barley Powder, 30 sachets each</li><li>Entry point for exploring the SANTÉ opportunity</li><li><strong>40% discount</strong></li><li>Choose your country before continuing</li>';if(!right.querySelector('.package-discount')){const badge=document.createElement('div');badge.className='package-discount';badge.textContent='✨ 40% Discount';const list=right.querySelector('ul');if(list)right.insertBefore(badge,list)};cards.forEach((card,i)=>{card.querySelectorAll('a,button').forEach(t=>{if(t.closest('.package-image-wrap'))return;t.onclick=e=>{e.preventDefault();choose(i===0?'preferred':'intro')};if(t.tagName==='A'){t.href=links[i===0?'preferred':'intro'].ph;t.removeAttribute('target')}})});addBusinessPackages(section)}
  apply();
})();
