/* Premium SANTÉ Business Packages visual redesign. Keeps existing package inclusions and registration destinations. */
(function(){
  const packages=[
    {key:'starter',stars:1,label:'STARTER PACKAGE',owner:'1 Star Business Owner',title:'Start your SANTÉ business journey',items:['2 boxes of SANTÉ Barley Powder, 30 sachets each','1 SANTÉ Barley Canister, 200g'],images:['images1/sante-barley-powder.png','images1/sante-barley-jar-stevia.png']},
    {key:'builder',stars:2,label:'BUILDER PACK',owner:'2 Star Business Owner',title:'Build your product foundation',items:['5 boxes of SANTÉ Barley Powder, 30 sachets each','3 boxes of Barley Trial Pack, 10 sachets each','4 SANTÉ Barley Canisters, 200g each'],images:['images1/sante-barley-powder.png','images1/sante-barley-trial-pack.png','images1/sante-barley-jar-stevia.png']},
    {key:'extreme',stars:3,label:'EXTREME PACK',owner:'3 Star Business Owner',title:'Take your business journey further',items:['13 boxes of SANTÉ Barley Powder, 30 sachets each','8 boxes of Barley Trial Pack, 10 sachets each','9 SANTÉ Barley Canisters, 200g each'],images:['images1/sante-barley-powder.png','images1/sante-barley-trial-pack.png','images1/sante-barley-jar-stevia.png']},
    {key:'ultimate',stars:4,label:'ULTIMATE PACK',owner:'4 Star Business Owner',title:'A larger package for your next step',items:['32 boxes of SANTÉ Barley Powder, 30 sachets each','22 boxes of Barley Trial Pack, 10 sachets each','22 SANTÉ Barley Canisters, 200g each'],images:['images1/sante-barley-powder.png','images1/sante-barley-trial-pack.png','images1/sante-barley-jar-stevia.png']},
    {key:'global',stars:5,label:'GLOBAL ULTIMATE / GLOBAL FRANCHISEE',owner:'5 Star Business Owner',title:'Explore the Global Ultimate package',items:['45 boxes of SANTÉ Barley Powder, 30 sachets each','45 boxes of Barley Trial Pack, 10 sachets each','45 SANTÉ Barley Canisters, 200g each','45 boxes of SANTÉ Barley Capsules, 60 veggie caps per box'],images:['images1/sante-barley-powder.png','images1/sante-barley-trial-pack.png','images1/sante-barley-jar-stevia.png','images1/sante-barley-capsule.png']}
  ];
  const links={
    preferred:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=preferred',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=preferred'},
    intro:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=intro',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=intro'},
    starter:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=starter',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=starter'},
    builder:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=builder',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=builder'},
    extreme:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=extreme',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=extreme'},
    ultimate:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=ultimate',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=ultimate'},
    global:{ph:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=PH&package=global',global:'https://partner.mysante.com/epackage?ref=WEALTHYLORE&country=GLOBAL&package=global'}
  };
  function stars(n){return '<span class="bp-star-line">'+Array(n).fill('★').join('')+'</span>'}
  function addStyle(){if(document.getElementById('sante-business-premium-style'))return;const s=document.createElement('style');s.id='sante-business-premium-style';s.textContent=`
#business-packages.business-packages{position:relative;margin:72px auto 0;padding:54px 28px 28px;max-width:1580px;overflow:hidden;background:radial-gradient(circle at 8% 0,#e8f3ea 0,transparent 26%),radial-gradient(circle at 94% 12%,#e6f1e9 0,transparent 25%),linear-gradient(180deg,#f8fbf8,#f1f6f2);border:1px solid #dbe8de;border-radius:34px;box-shadow:0 18px 50px rgba(16,61,43,.08)}
#business-packages:before,#business-packages:after{content:'';position:absolute;width:220px;height:220px;border-radius:50%;filter:blur(3px);opacity:.18;background:#2e8b57;pointer-events:none}#business-packages:before{left:-130px;top:80px}#business-packages:after{right:-140px;top:-110px}
.business-packages-head{position:relative;z-index:1;max-width:760px;margin:0 auto 34px;text-align:center}.business-packages-head .eyebrow{display:block;margin-bottom:10px;color:#2b7a4b;font-weight:900;letter-spacing:.24em;font-size:.76rem}.business-packages-head h2{margin:0;color:#18382a;font-size:clamp(2rem,4vw,3.4rem);line-height:1.04}.business-packages-head p:last-child{margin:13px auto 0;max-width:620px;color:#617169;line-height:1.65}
.business-package-grid{position:relative;z-index:1;display:grid;grid-template-columns:repeat(5,minmax(0,1fr));gap:14px;align-items:stretch}.business-package-card{--accent:#1f7548;position:relative;display:flex;flex-direction:column;min-width:0;padding:18px 16px 16px;border:1px solid rgba(32,81,57,.14);border-radius:25px;background:rgba(255,255,255,.88);box-shadow:0 10px 28px rgba(17,61,43,.08);transition:transform .22s ease,box-shadow .22s ease,border-color .22s ease;overflow:hidden}.business-package-card:hover{transform:translateY(-7px);box-shadow:0 22px 42px rgba(17,61,43,.15);border-color:var(--accent)}.business-package-card:nth-child(2){--accent:#2671a8}.business-package-card:nth-child(3){--accent:#c47713}.business-package-card:nth-child(4){--accent:#7651aa}.business-package-card:nth-child(5){--accent:#9b6700}
.business-package-card:last-child{grid-column:auto}.bp-tier{display:flex;align-items:center;gap:10px;min-height:42px}.bp-stars{display:flex;align-items:center;justify-content:center;min-width:54px;padding:8px 11px;border-radius:999px;background:#fff;box-shadow:0 4px 12px rgba(23,70,45,.08);color:var(--accent);font-size:.92rem;letter-spacing:1px}.bp-tier-text{font-size:.73rem;line-height:1.2;font-weight:900;letter-spacing:.06em;color:#455b51}.bp-tier-text span{display:block;color:var(--accent);margin-top:3px;font-size:.68rem}.business-package-eyebrow{margin-top:18px;color:var(--accent);font-size:.69rem;font-weight:900;letter-spacing:.16em}.business-package-card h3{margin:8px 0 4px;color:#1d3b2e;font-size:1.25rem;line-height:1.18}.business-package-owner{margin:0;color:#66776f;font-size:.86rem;font-weight:750}
.bp-products{height:145px;margin:12px 0 10px;display:flex;align-items:center;justify-content:center;gap:1px;padding:6px 0;background:linear-gradient(180deg,rgba(237,246,239,.8),rgba(255,255,255,0));border-radius:18px}.bp-products img{max-width:48%;max-height:130px;object-fit:contain;filter:drop-shadow(0 10px 10px rgba(13,57,36,.14));transition:transform .25s ease}.business-package-card:hover .bp-products img{transform:translateY(-3px) scale(1.02)}.bp-products.four img{max-width:31%}
.business-package-card ul{list-style:none;padding:0;margin:0 0 14px;color:#42564c;font-size:.82rem;line-height:1.35}.business-package-card li{position:relative;padding:4px 0 4px 20px}.business-package-card li:before{content:'✓';position:absolute;left:0;top:4px;color:var(--accent);font-weight:1000}.business-package-choice{margin-top:auto;min-height:82px;padding:11px 12px 11px 40px;border-radius:14px;background:linear-gradient(135deg,rgba(230,241,233,.92),rgba(248,246,236,.9));color:#50635a;font-size:.74rem;line-height:1.45;position:relative}.business-package-choice:before{content:'✦';position:absolute;left:14px;top:12px;color:var(--accent);font-size:1.05rem}.bp-location-label{margin:16px 0 7px;text-align:center;font-size:.64rem;font-weight:900;letter-spacing:.12em;color:#63736b}.bp-location-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.bp-location-actions a{display:flex;align-items:center;justify-content:center;gap:5px;min-height:42px;padding:8px 6px;border:1px solid color-mix(in srgb,var(--accent) 40%,#d8e3dc);border-radius:11px;background:#fff;color:#29473a;text-decoration:none;font-size:.74rem;font-weight:850;cursor:pointer;transition:.2s}.bp-location-actions a:hover{background:#f1f8f3;border-color:var(--accent)}.bp-location-actions small{display:block;font-size:.58rem;font-weight:650;color:#7c8b83}.bp-choose{width:100%;margin-top:9px;border:0;border-radius:12px;padding:13px 10px;background:var(--accent);color:#fff;font:inherit;font-size:.76rem;font-weight:900;letter-spacing:.02em;cursor:pointer;box-shadow:0 7px 16px color-mix(in srgb,var(--accent) 28%,transparent);transition:.2s}.bp-choose:hover{filter:brightness(1.06);transform:translateY(-1px)}
.business-package-benefits{position:relative;z-index:1;display:grid;grid-template-columns:repeat(5,1fr);gap:0;margin-top:26px;padding:19px 4px 4px;border-top:1px solid #dbe6de}.bp-benefit{display:flex;gap:11px;padding:4px 16px;border-right:1px solid #dbe6de}.bp-benefit:last-child{border-right:0}.bp-benefit-icon{width:42px;height:42px;flex:0 0 42px;display:grid;place-items:center;border-radius:50%;background:#e7f2e9;color:#26764a;font-size:1.2rem}.bp-benefit strong{display:block;color:#264334;font-size:.78rem}.bp-benefit span{display:block;margin-top:4px;color:#6a786f;font-size:.68rem;line-height:1.35}
.package-location-modal[hidden]{display:none!important}.package-location-modal{position:fixed;inset:0;z-index:11000;display:grid;place-items:center;padding:20px;background:#0d251b7a}.package-location-box{width:min(560px,100%);background:#fff;border-radius:24px;padding:34px;box-shadow:0 25px 70px #103d2b47}.package-location-box h2{margin:0 0 10px;color:#19352a}.package-location-actions{display:grid;grid-template-columns:1fr 1fr;gap:12px;margin-top:22px}.package-location-actions a{display:block;padding:16px;border:1px solid #dce6df;border-radius:16px;text-decoration:none;color:#19352a;font-weight:800;background:#f8f8f4}.package-location-close{margin-top:18px;border:0;background:transparent;font:inherit;color:#496158;cursor:pointer}
@media(max-width:1250px){.business-package-grid{grid-template-columns:repeat(3,minmax(0,1fr))}.business-package-card:nth-child(4),.business-package-card:nth-child(5){grid-column:auto}.business-package-benefits{grid-template-columns:repeat(3,1fr)}.bp-benefit:nth-child(3){border-right:0}.bp-benefit:nth-child(n+4){margin-top:14px}}
@media(max-width:820px){#business-packages.business-packages{margin-top:50px;padding:42px 18px 22px;border-radius:26px}.business-package-grid{grid-template-columns:repeat(2,minmax(0,1fr))}.business-package-benefits{grid-template-columns:repeat(2,1fr)}.bp-benefit:nth-child(2){border-right:0}.bp-benefit:nth-child(3){border-right:1px solid #dbe6de}.bp-benefit:nth-child(n+3){margin-top:14px}}
@media(max-width:600px){#business-packages.business-packages{padding:36px 12px 16px;border-radius:20px}.business-package-grid{grid-template-columns:1fr;gap:12px}.business-package-card{padding:20px 16px}.business-package-card h3{font-size:1.35rem}.bp-products{height:160px}.business-package-benefits{grid-template-columns:1fr}.bp-benefit,.bp-benefit:nth-child(3){border-right:0;border-bottom:1px solid #e0e8e2;padding:10px 8px}.bp-benefit:last-child{border-bottom:0}.package-location-actions{grid-template-columns:1fr}}
`;document.head.appendChild(s)}
  function modal(){let m=document.querySelector('.package-location-modal');if(m)return m;m=document.createElement('div');m.className='package-location-modal';m.hidden=true;m.innerHTML='<div class="package-location-box" role="dialog" aria-modal="true"><h2>Choose your location</h2><p>Select where you are registering from to continue to the exact SANTÉ package page.</p><div class="package-location-actions"><a class="package-ph" target="_blank" rel="noopener">🇵🇭 Philippines</a><a class="package-global" target="_blank" rel="noopener">🌎 Global / Outside the Philippines</a></div><button class="package-location-close" type="button">← Cancel</button></div>';document.body.appendChild(m);const close=()=>m.hidden=true;m.querySelector('.package-location-close').onclick=close;m.onclick=e=>{if(e.target===m)close()};return m}
  function choose(key){const m=modal(),d=links[key];m.querySelector('.package-ph').href=d.ph;m.querySelector('.package-global').href=d.global;m.hidden=false}
  function packageCard(p){const imgs=p.images.map((src,i)=>`<img src="${src}" alt="SANTÉ Barley package product ${i+1}" loading="lazy" onerror="this.style.display='none'">`).join('');const tier=`<div class="bp-tier"><div class="bp-stars">${stars(p.stars)}</div><div class="bp-tier-text">${p.stars} STAR<span>${p.owner.toUpperCase()}</span></div></div>`;return `<article class="business-package-card">${tier}<div class="business-package-eyebrow">${p.label}</div><h3>${p.title}</h3><p class="business-package-owner">${p.owner}</p><div class="bp-products ${p.images.length===4?'four':''}">${imgs}</div><ul>${p.items.map(x=>'<li>'+x+'</li>').join('')}</ul><div class="business-package-choice">Product selection options may be available during registration, allowing you to choose products you prefer where applicable.</div><div class="bp-location-label">CHOOSE YOUR LOCATION</div><div class="bp-location-actions"><a href="${links[p.key].ph}" target="_blank" rel="noopener">🇵🇭 Philippines</a><a href="${links[p.key].global}" target="_blank" rel="noopener">🌎 Global <small>Outside PH</small></a></div><button class="bp-choose" type="button">Choose ${p.label.replace(' / GLOBAL FRANCHISEE','')} →</button></article>`}
  function addBusinessPackages(section){const old=document.getElementById('business-packages');if(old)old.remove();const wrap=document.createElement('section');wrap.id='business-packages';wrap.className='business-packages';wrap.innerHTML='<div class="business-packages-head"><span class="eyebrow">BUILD YOUR FUTURE</span><h2>SANTÉ Business Packages</h2><p>Choose the package that matches your starting point and review the exact included products before continuing to registration.</p></div><div class="business-package-grid">'+packages.map(packageCard).join('')+'</div><div class="business-package-benefits"><div class="bp-benefit"><div class="bp-benefit-icon">↗</div><div><strong>Business Opportunity</strong><span>Explore a flexible opportunity around your goals.</span></div></div><div class="bp-benefit"><div class="bp-benefit-icon">◎</div><div><strong>Global Community</strong><span>Connect with a growing international community.</span></div></div><div class="bp-benefit"><div class="bp-benefit-icon">✦</div><div><strong>Product Selection</strong><span>Choose preferred products where applicable.</span></div></div><div class="bp-benefit"><div class="bp-benefit-icon">★</div><div><strong>Incentives & Rewards</strong><span>Learn about available program incentives.</span></div></div><div class="bp-benefit"><div class="bp-benefit-icon">♡</div><div><strong>Support & Training</strong><span>Get guidance and information from Lore.</span></div></div></div>';const grid=wrap.querySelector('.business-package-grid');grid.querySelectorAll('.bp-choose').forEach((btn,i)=>btn.addEventListener('click',()=>choose(packages[i].key)));section.parentNode.insertBefore(wrap,section.nextSibling)}
  function apply(){const section=document.querySelector('.package-restore');if(!section)return setTimeout(apply,150);addStyle();addBusinessPackages(section)}
  apply();
})();